version: "3.2"
services:
  babycsp:
    restart: always
    build: './'
    ports:
      - "127.0.0.1:2087:5000"
    logging:
        driver: "json-file"
        options:
            max-file: "1"
            max-size: "10m"
networks:
    default:
        driver_opts:
            com.docker.network.bridge.name: babycspwebctfit